-- MySQL Script generated by MySQL Workbench
-- Mon Oct  3 19:57:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb_new
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_new
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_new` DEFAULT CHARACTER SET utf8 ;
USE `mydb_new` ;

-- -----------------------------------------------------
-- Table `mydb_new`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_new`.`member` (
  `ID` INT NOT NULL,
  `Password` VARCHAR(15) NULL DEFAULT NULL,
  `User_name` VARCHAR(10) NULL DEFAULT NULL,
  `Phone_number` VARCHAR(10) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb_new`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_new`.`administrator` (
  `Administrator_ID` INT NOT NULL,
  `member_ID` INT NOT NULL,
  PRIMARY KEY (`Administrator_ID`, `member_ID`),

  CONSTRAINT `fk_administrator_member1`
    FOREIGN KEY (`member_ID`)
    REFERENCES `mydb_new`.`member` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb_new`.`fish_industry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_new`.`fish_industry` (
  `Fish_Industry_ID` INT NOT NULL,
  `Fishing_boat_name` VARCHAR(10) NULL DEFAULT NULL,
  `Fishing_area` VARCHAR(10) NULL DEFAULT NULL,
  `Fishing_license_number` VARCHAR(10) NULL DEFAULT NULL,
  `member_ID` INT NOT NULL,
  PRIMARY KEY (`Fish_Industry_ID`, `member_ID`),

  CONSTRAINT `fk_fish_industry_member1`
    FOREIGN KEY (`member_ID`)
    REFERENCES `mydb_new`.`member` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb_new`.`record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_new`.`record` (
  `Record_ID` INT NOT NULL,
  `Fishing_area` VARCHAR(15) NULL DEFAULT NULL,
  `catch_date` DATE NULL DEFAULT NULL,
  `photo` VARCHAR(500) NULL DEFAULT NULL,
  `fingerlings` VARCHAR(10) NULL DEFAULT NULL,
  `yield_of_catch` INT NULL DEFAULT NULL,
  `Violation_record` INT NULL DEFAULT NULL,
  `fish_industry_Fish_Industry_ID` INT NOT NULL,
  `administrator_Administrator_ID` INT NOT NULL,
  PRIMARY KEY (`Record_ID`, `fish_industry_Fish_Industry_ID`, `administrator_Administrator_ID`),

  CONSTRAINT `fk_record_fish_industry1`
    FOREIGN KEY (`fish_industry_Fish_Industry_ID`)
    REFERENCES `mydb_new`.`fish_industry` (`Fish_Industry_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_administrator1`
    FOREIGN KEY (`administrator_Administrator_ID`)
    REFERENCES `mydb_new`.`administrator` (`Administrator_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb_new`.`announcement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_new`.`announcement` (
  `announcement_id` INT NOT NULL,
  `date` DATE NULL,
  `content` VARCHAR(45) NULL,
  `administrator_Administrator_ID` INT NOT NULL,
  `fish_industry_Fish_Industry_ID` INT NOT NULL,
  PRIMARY KEY (`announcement_id`, `administrator_Administrator_ID`),


  CONSTRAINT `fk_announcement_administrator1`
    FOREIGN KEY (`administrator_Administrator_ID`)
    REFERENCES `mydb_new`.`administrator` (`Administrator_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_announcement_fish_industry1`
    FOREIGN KEY (`fish_industry_Fish_Industry_ID`)
    REFERENCES `mydb_new`.`fish_industry` (`Fish_Industry_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
