-- MySQL Script generated by MySQL Workbench
-- Wed Apr 20 22:27:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Fish Industry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fish Industry` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fish Industry` (
  `Fish Industry_ID` INT NOT NULL,
  `Fishing boat name` VARCHAR(8) NULL,
  `Fishing area` VARCHAR(8) NULL,
  `Fishing license number` VARCHAR(8) NULL,
  `Fish Industrycol` VARCHAR(8) NULL,
  PRIMARY KEY (`Fish Industry_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`store` ;

CREATE TABLE IF NOT EXISTS `mydb`.`store` (
  `store_ID` INT NOT NULL,
  `Address` VARCHAR(8) NULL,
  `Name` VARCHAR(8) NULL,
  PRIMARY KEY (`store_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Administrator` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Administrator` (
  `Administrator_ID` INT NOT NULL,
  PRIMARY KEY (`Administrator_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Member` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Member` (
  `ID` INT NOT NULL,
  `Password` VARCHAR(8) NULL,
  `User name` VARCHAR(8) NULL,
  `Phone number` VARCHAR(8) NULL,
  `Email` VARCHAR(8) NULL,
  `Fish Industry_Fish Industry_ID` INT NOT NULL,
  `store_store_ID` INT NOT NULL,
  `Administrator_Administrator_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Fish Industry_Fish Industry_ID`, `store_store_ID`, `Administrator_Administrator_ID`),

  CONSTRAINT `fk_Member_Fish Industry1`
    FOREIGN KEY (`Fish Industry_Fish Industry_ID`)
    REFERENCES `mydb`.`Fish Industry` (`Fish Industry_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Member_store1`
    FOREIGN KEY (`store_store_ID`)
    REFERENCES `mydb`.`store` (`store_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Member_Administrator1`
    FOREIGN KEY (`Administrator_Administrator_ID`)
    REFERENCES `mydb`.`Administrator` (`Administrator_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Record` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Record` (
  `Record_ID` INT NOT NULL,
  `Fishing area` VARCHAR(15) NULL,
  `sale date` DATE NULL,
  `video` VARCHAR(45) NULL,
  `fingerlings` VARCHAR(8) NULL,
  `yield of catch` INT NULL,
  `Violation record` INT NULL,
  `Fish Industry_Fish Industry_ID` INT NOT NULL,
  `store_store_ID` INT NOT NULL,
  `Administrator_Administrator_ID` INT NOT NULL,
  PRIMARY KEY (`Record_ID`, `Fish Industry_Fish Industry_ID`, `store_store_ID`, `Administrator_Administrator_ID`),

  CONSTRAINT `fk_Record_Fish Industry`
    FOREIGN KEY (`Fish Industry_Fish Industry_ID`)
    REFERENCES `mydb`.`Fish Industry` (`Fish Industry_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Record_store1`
    FOREIGN KEY (`store_store_ID`)
    REFERENCES `mydb`.`store` (`store_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Record_Administrator1`
    FOREIGN KEY (`Administrator_Administrator_ID`)
    REFERENCES `mydb`.`Administrator` (`Administrator_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
